# Generated by Django 4.1.4 on 2023-03-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PodcastRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("podcast_title", models.CharField(max_length=100)),
                ("podcast_details", models.TextField()),
            ],
        ),
    ]
