# Generated by Django 4.2 on 2023-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filesharing", old_name="myimage", new_name="my_title",
        ),
        migrations.AddField(
            model_name="filesharing",
            name="my_image",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="news/"
            ),
        ),
    ]
