# Generated by Django 4.2 on 2023-05-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="myToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toDoListData", models.CharField(max_length=250)),
                ("status", models.BooleanField()),
            ],
        ),
    ]
