# Generated by Django 4.2 on 2023-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee", name="phone", field=models.CharField(max_length=12),
        ),
    ]
